name: Docker Image Build + Scan + Publish
on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "Dockerfile"
      - ".github/workflows/build-push.yml"
  workflow_dispatch:

# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: ci-${{ github.repository }}-docker-pipeline

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  docker-image-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ vars.role_to_assume_tf_state }}
          aws-region: ${{ vars.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: prepare ECR repo name based on the Github repository
        shell: bash
        run: |
          set -eux
          # lowercase the name
          repo="${GITHUB_REPOSITORY,,}"

          # replace / with _
          echo "ECR_REPO_NAME=${repo//\//_}" >> $GITHUB_ENV

      - name: Set image tag (default = short commit SHA)
        shell: bash
        run: |
          set -eux
          tag="${{ vars.image_tag }}-${GITHUB_SHA::7}"
          echo "IMAGE_TAG=$tag" >> "$GITHUB_ENV"
          
          testingTag="${GITHUB_SHA::7}"
          echo "Testing_TAG=$testingTag" >> "$GITHUB_ENV"

      - name: Build an image from Dockerfile
        run: docker build -t ${{ vars.image_tag }}:${{ env.Testing_TAG }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ vars.image_tag }}:${{ env.Testing_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: TF init
        shell: bash
        run: |
          set -eux
          terraform init -upgrade -reconfigure \
            -backend-config='skip_metadata_api_check=true' \
            -backend-config='skip_region_validation=true' \
            -backend-config='skip_credentials_validation=true' \
            -backend-config='region=${{ vars.aws_region }}' \
            -backend-config='bucket=${{ vars.backend_s3_bucket }}' \
            -backend-config='key=${{ vars.ecr_key }}' \
            -backend-config='use_lockfile=true' \
        working-directory: ecr_bootstrap

      - name: Create ECR repo [TF apply]
        shell: bash
        run: |
          set -eux
          terraform apply \
            -var 'repository_name=${{ env.ECR_REPO_NAME }}' \
            -var 'lifecycle_policy=${{ vars.lifecycle_policy_file }}' \
            -var 'iam_role=arn:aws:iam::${{ vars.aws_account_id }}:role/${{ vars.githubb_iam_role }}' \
            -var 'aws_account_id=${{ vars.aws_account_id }}' \
            -auto-approve
        working-directory: ecr_bootstrap

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ vars.aws_account_id }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -f "${{ vars.path_to_dockerfile }}" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" .
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
